# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: yt-dlg.yt-dlg
PackageVersion: 1.8.2
PackageLocale: en-US
Publisher: yt-dlg
PackageName: yt-dlg
License: Unlicense
ShortDescription: A cross platform front-end GUI of the popular youtube-dl written in wxPython.
ManifestType: defaultLocale
ManifestVersion: 1.0.0

